{
    "Properties": {
        "ObjectKey": "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetCompleteObjectKey.js",
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusCompleted.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/EndDateTime.js"
    },
    "Target": {
        "EntitySet": "MobileStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink" : "/SAPAssetManager/Rules/MobileStatus/MobileStatusSetCompleteReadLink.js"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
}
