{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "/SAPAssetManager/Rules/Notes/NoteGetEntitySet.js",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "/SAPAssetManager/Rules/Notes/NoteReadlink.js"
    },
    "Properties": {
        "NotificationNumber": "/SAPAssetManager/Rules/Notifications/ChangesetSwitchNotificationID.js",
        "ItemNumber": "/SAPAssetManager/Rules/Notifications/Item/GenerateNotificationItemID.js",
        "CauseSequenceNumber": "/SAPAssetManager/Rules/Notifications/Item/Cause/GenerateNotificationItemCauseID.js",
        "NewTextString": "",
        "TextString": "/SAPAssetManager/Rules/Notes/NoteRemoteTextString.js"
    },
    "Headers": {
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/ChangesetSwitchNotificationID.js"
    },
	"OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntitySuccessMessage.action",
    "OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/DeleteEntityFailureMessage.action",
    "UpdateLinks": "/SAPAssetManager/Rules/Notes/NoteCreateLinks.js"
}