{
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ZEQL_C_FORMIO",
			"Query": "ZEQL_C_FORMIO"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ZEQ_FORMIODATA_C",
			"Query": "ZEQ_FORMIODATA_C"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ZEQL_C_FORMIOASSIGN",
			"Query": "ZEQL_C_FORMIOASSIGN"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ZEQL_C_FORMIOMAP",
			"Query": "ZEQL_C_FORMIOMAP"
		}
	],
	"Service": "/SAPAssetManager/Services/Formio.service",
	"_Type": "Action.Type.OfflineOData.Download"
}