{
	"_Type": "Action.Type.CheckRequiredFields",
	"RequiredFields":[
		"Order",
		"OperationLstPkr",
		"PartCategoryLstPkr",
		"PlantLstPkr",
		"TextItemSim",
		"QuantitySim"
	],
	"OnSuccess":"/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateOnCommit.js",
	"OnFailure":"/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js"
}