{
    "Properties":
	{
        "PartnerFunction": "/SAPAssetManager/Rules/Common/Partner/PartnerFunctionForPersonelNumber.js",
        "PartnerNum": "/SAPAssetManager/Rules/Common/Partner/PartnerPersonnelNumber.js"
    },
    "Target":
	{
        "EntitySet": "MyNotificationPartners",
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "Headers":
	{
        "OfflineOData.RemoveAfterUpload": "true",
        "OfflineOData.TransactionID": "/SAPAssetManager/Rules/Notifications/GenerateNotificationID.js"
    },
	"CreateLinks":
	[{
		"Property" : "Notification",
		"Target":
		{
			"EntitySet" : "MyNotificationHeaders",
			"ReadLink" : "pending_1"
		}
	}],
    "_Type": "Action.Type.ODataService.CreateEntity"
}