{
    "_Type" : "Action.Type.Navigation",
    "PageToOpen" : "/SAPAssetManager/Pages/Extensions/MeasuringPointsDataEntry.page",
    "ShowActivityIndicator" : false,
    "ActivityIndicatorText" : " ",
    "ModalPage": true
}
