{
    "Properties": {
        "ObjectKey": "#Property:ObjectKey",
        "ObjectType": "/SAPAssetManager/Rules/WorkOrders/WorkOrderObjectType.js",
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/MobileStatusStarted.js",
        "EffectiveTimestamp": "/SAPAssetManager/Rules/DateTime/StartDateTime.js"
    },
    "Target": {
        "EntitySet": "MobileStatuses",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink" : "/SAPAssetManager/Rules/MobileStatus/MobileStatusReadLink.js"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
}