{
    "Actions": "/SAPAssetManager/Rules/Checklists/FormAssessmentQuestionUpdate.js",
    "OnSuccess": "/SAPAssetManager/Rules/Checklists/ChecklistFDCUpdateSuccess.js",
    "OnFailure": "/SAPAssetManager/Rules/Common/ChangeSet/ChangeSetOnFailure.js",
    "Target": {
        "Service": "/SAPAssetManager/Services/AssetManager.service"
    },
    "_Type": "Action.Type.ODataService.ChangeSet"
}
