{
    "Target":
    {
        "EntitySet": "Forms",
        "Service": "/SAPAssetManager/Services/AssetManager.service",
        "ReadLink": "{{#Property:Form_Nav/#Property:@odata.readLink}}"
    },
    "Properties":
    {
        "MobileStatus": "/SAPAssetManager/Rules/MobileStatus/Checklist/ChecklistMobileStatusInProgress.js",
        "Status": "0"
    },
    "Headers":
	{
        "Transaction.Ignore": "true",
        "OfflineOData.TransactionID": "#Property:AssessmentId"
    },
    "_Type": "Action.Type.ODataService.UpdateEntity"
}