{
    "_Type": "Action.Type.ODataService.CreateMedia",
    "Target" : {
      "EntitySet" : "Documents",
      "Service" : "/SAPAssetManager/Services/AssetManager.service"
    },
    "Headers" : {
       "slug" : {
          "ObjectLink":"/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateObjectLink.js",
          "ObjectKey": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateKey.js",
          "FileName": "{FileName}",
          "Description": "/SAPAssetManager/Rules/Documents/Create/OnCreateGetDocDescription.js"
      }
    },
    "Properties" : {
        "ObjectLink": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateObjectLink.js",
        "ObjectKey": "/SAPAssetManager/Rules/Documents/DocumentTransactionID.js",
        "FileName": "{FileName}",
        "Description": "/SAPAssetManager/Rules/Documents/Create/OnCreateGetDocDescription.js",
        "MimeType": "{contentType}"
    },
    "IsOnlineRequest": false,
    "Media":"{attachment}",
    "OnFailure": "/SAPAssetManager/Rules/Documents/Create/DocumentOnCreateFailure.js"
  }