{
    "OnFailure": "/SAPAssetManager/Rules/Common/UpdateRequiredFailed.js",
    "OnSuccess": "/SAPAssetManager/Rules/Notifications/Item/CreateUpdate/NotificationItemCreateUpdateOnCommit.js",
    "RequiredFields": [
        "NameTitle",
        "PartGroupLstPkr",
        "PartDetailsLstPkr",
        "DamageGroupLstPkr",
        "DamageDetailsLstPkr"
    ],
    "_Type": "Action.Type.CheckRequiredFields",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText" : " "
}
